# Site settings
title: Katie Murray's personal website
author:
  name: Katie Murray
  email: kmurray@stsci.edu
description: "Information about Katie, Science Support Analyst I at STScI"

# Build settings
remote_theme: daviddarnes/alembic
